### ISSUE TITLE
Remove disallowed actions from janitors

### ISSUE THREAD

**Issue by salasberryfin** [rancher/highlander#106]
# Description

All janitors ([aws](https://github.com/rancher/aws-janitor/blob/68a6919bc0c4c00105f10fc95b8105dee7f619a7/.github/workflows/release.yml#L52), [azure](https://github.com/rancher/azure-janitor/blob/90a1ba53f7e37ad1e1a20455efe355c06849d84e/.github/workflows/release.yml#L52) and [gcp](https://github.com/rancher-sandbox/gcp-janitor/blob/a26ad042cc51fee265a080d862af88e5c3b11bc0/.github/workflows/release.yaml#L52)) use a release GitHub Action `softprops/action-gh-release` that is not allowed by EIO rules.

We need to get rid of this action and use one that is in the following list https://github.com/rancher/security-team/blob/main/docs/rancher-gha-standards.md#allowed-github-actions

**Comment by furkatgofurov7** [comment]
All PRs' merged now, closing it
