### ISSUE TITLE
Forked CAPZ/CAPG not referencing prime images

### ISSUE THREAD

**Issue by salasberryfin** [rancher/highlander#110]
# Description

CAPZ and CAPG forked releases are still referencing upstream Kubernetes images while release action performs proper substitution for CAPA in yaml file.

Examples:
- CAPZ [v1.17.0](https://github.com/rancher-sandbox/cluster-api-provider-azure/releases/tag/v1.17.0)
- CAPG [v0.8.0](https://github.com/rancher-sandbox/cluster-api-provider-gcp/releases/tag/v1.8.0)

We should take a look at what the differences are between CAPA and CAPZ/CAPG release processes and identify how we can publish a release with the proper values.

**Comment by alexander-demicev** [comment]
this was fixed by https://github.com/rancher/turtles/pull/874
