### ISSUE TITLE
GKE 2.7.6 Validation

### ISSUE THREAD

**Issue by cpinjani** [rancher/highlander#26]
QA validation for v2.7.6

- [x]  Regression checks
- [x]  P0 checks
- [x]  Support matrix checks, Validate all versions of hosted downstream clusters works as expected on latest Rancher
- [x]  Terraform provider
 
The validation procedure follows [this guide](https://confluence.suse.com/pages/viewpage.action?spaceKey=RANQA&title=Hosted+Clusters+Validations+in+Rancher+Releases).

**Comment by valaparthvi** [comment]
Done with P0 and Regression checks. They work well.

**Comment by valaparthvi** [comment]
> Support matrix checks, Validate all versions of hosted downstream clusters works as expected on latest Rancher

Tested with GKE 1.23, 1.24, 1.25, and 1.26. All work as expected.

**Comment by valaparthvi** [comment]
Discovered a few UI bugs:
https://github.com/rancher/dashboard/issues/9507

**Comment by valaparthvi** [comment]
/close

Tested against v2.7.6-head image tag, things work as expected.
