### ISSUE TITLE
Rancher provisioning overrides the operator nightly chart image

### ISSUE THREAD

**Issue by cpinjani** [rancher/highlander#35]
**Steps:**
- Start Rancher Manager with CATTLE_SKIP_HOSTED_CLUSTER_CHART_INSTALLATION set to true.
`helm install rancher rancher-latest/rancher --namespace cattle-system --set bootstrapPassword=admin --set replicas=1 --set hostname=my.host.dev --set global.cattle.psp.enabled=false --set 'extraEnv[0].name=CATTLE_SKIP_HOSTED_CLUSTER_CHART_INSTALLATION' --set 'extraEnv[0].value="true"' --version 2.7.5`

- Install the chart using the tag for the day:
```
helm install rancher-eks-operator-crd oci://ttl.sh/eks-operator/rancher-eks-operator-crd --version 20230621 --namespace cattle-system
helm install rancher-eks-operator oci://ttl.sh/eks-operator/rancher-eks-operator --version 20230621 --namespace cattle-system
```
- Check nightly chart installed:

![image](https://github.com/rancher/highlander/assets/73099870/b18a5672-4279-4d4d-b858-d48f4ff53436)

![image](https://github.com/rancher/highlander/assets/73099870/1f37dc3b-5617-4470-b3f7-895e2e313b24)

- Provision the hosted downstream cluster, this overrides the nightly chart and sets it to current supported one.
![image](https://github.com/rancher/highlander/assets/73099870/6adb1fcd-6c17-4b8e-8f94-0551bca21a2b)

**Expected Results**
Nightly chart must be used for provisioning and must not be overridden.

cc: @richardcase

**Comment by alexander-demicev** [comment]
Hi, I can't reproduce it, this is the command I used to deploy rancher
```
helm install rancher rancher-stable/rancher     --namespace cattle-system     --create-namespace     --set bootstrapPassword=rancheradmin     --set replicas=1     --set hostname="$RANCHER_HOSTNAME"     --set 'extraEnv[0].name=CATTLE_SKIP_HOSTED_CLUSTER_CHART_INSTALLATION'     --set-string 'extraEnv[0].value=true'     --set global.cattle.psp.enabled=false     --version v2.7.5     --wait
```

**Comment by cpinjani** [comment]
@alexander-demicev Thanks for the command, its working now.
I fixed our internal Confluence page where parameter to set extraEnv was not accurate.
