### ISSUE TITLE
Build upstream CAPI

### ISSUE THREAD

**Issue by richardcase** [rancher/highlander#47]
Build [our fork](https://github.com/rancher-sandbox/cluster-api) of upstream CAPI using GitHub actions and publish to prime registry (along with slsa provenance).

A couple of things to consider:

- We'll need to do this for some other providers, so let's try and use reusable workflows as much as possible.
- If we can automatically detect a new upstream release and start the rebase/build of the form that would be excellent

**Comment by richardcase** [comment]
From CAPI Operator:

- Image override
- Pull location (better UX than specifying fetch URL)
- Air-gapped bundling already done

**Comment by Danil-Grigorev** [comment]
CAPI Operator will be able to support image overrides with https://github.com/kubernetes-sigs/cluster-api-operator/pull/349

**Comment by richardcase** [comment]
As we are waiting EIO to add the prime details lets start publishing to GHCR and we can create a separate issue to enable the prime publication as a follow-up.

**Comment by richardcase** [comment]
We can make the GHCR images public.

**Comment by richardcase** [comment]
From planning, just publish to prime registry.

**Comment by alexander-demicev** [comment]
https://github.com/rancherlabs/eio/issues/2462
