### ISSUE TITLE
Prepare talk for cloud-native-rejekts

### ISSUE THREAD

**Issue by Danil-Grigorev** [rancher/highlander#58]
Prepare a talk for the conference, slides, demo.
Demo will include using fleet as a gitops solution, applying and modifying CAPI Operator manifests. Rancher-turtles use-case will be mentioned in the slides. 
Current WIP doc: https://docs.google.com/document/d/1-1f52satVyqaj0c4HrjSFXzXeNHTs-my_AmLsWOwmes/edit

**Comment by kkaempf** [comment]
considered done
