### ISSUE TITLE
move rancher-turtles to rancher/turtles

### ISSUE THREAD

**Issue by kkaempf** [rancher/highlander#65]
Repo transfer

**Comment by richardcase** [comment]
This isn't strictly needed. What is more important is #67

**Comment by richardcase** [comment]
Created the EIO issue to do the move: https://github.com/rancherlabs/eio/issues/2105

**Comment by richardcase** [comment]
Created EIO issue to move the docs repo: https://github.com/rancherlabs/eio/issues/2109

**Comment by richardcase** [comment]
Completed.
