### ISSUE TITLE
Prepare a Demo for SA

### ISSUE THREAD

**Issue by mbologna** [rancher/highlander#73]
Prepare a demo, based on what we do for prospect customers, to show turtles
Audience: technical, SAs
Context: show the magic of turtles to SAs who are going to show them to customers.
No need for troubleshooting, just demo with a wow effect.
Deadline: March 14th
@davidstauffer holds the invite

**Comment by richardcase** [comment]
Lets add the demo material including:

- script
- any yaml files

to our demos: https://github.com/rancher/highlander/tree/main/demos

**Comment by kkaempf** [comment]
Considered done.
