### ISSUE TITLE
[CAPA] Configure account for AMI publishing

### ISSUE THREAD

**Issue by richardcase** [rancher/highlander#84]
Work on upstream issue: https://github.com/kubernetes/k8s.io/issues/5010

This is to help move AMI publication from a VMWare owned account to a community owned account.

**Comment by richardcase** [comment]
PR: https://github.com/kubernetes/k8s.io/pull/6517

**Comment by richardcase** [comment]
Blocked on upstream reviews

**Comment by kkaempf** [comment]
upstream issue, closing for Highlander
