### ISSUE TITLE
Deprecate unapproved GHA used in workflows

### ISSUE THREAD

**Issue by alexander-demicev** [rancher/highlander#89]
Soon only [approved GHA](https://github.com/rancher/security-team/blob/main/docs/rancher-gha-standards.md#allowed-github-actions) will be allowed to be used in our workflows. We have some GHAs which are not approved and don't fit the criteria to be approved:

EKS/AKS/GKE Operators:

https://github.com/rancher/aks-operator/blob/archive/.github/workflows/apidiff.yaml#L14
https://github.com/rancher/aks-operator/blob/archive/.github/workflows/e2e.yaml#L75
https://github.com/rancher-sandbox/highlander-reusable-workflows/blob/main/.github/workflows/update-rancher-charts.yaml#L71

GKE 
https://github.com/rancher/gke-operator/blob/main/.github/workflows/update-rancher-charts.yaml#L59

Turtles
https://github.com/rancher/turtles/blob/main/.github/workflows/dependabot.yml#L30
https://github.com/rancher/turtles/blob/main/.github/workflows/nightly-test-release.yaml#L120
https://github.com/rancher/turtles/blob/main/.github/workflows/nightly-test-release.yaml#L158
https://github.com/rancher/turtles/blob/main/.github/workflows/pr-md-link-check.yaml#L18
https://github.com/rancher/turtles/blob/main/.github/workflows/pr_size_labeler.yml#L12
https://github.com/rancher/turtles/blob/main/.github/workflows/pr_type.yaml#L12
https://github.com/rancher/turtles/blob/main/.github/workflows/test_chart.yaml#L59

We need to deprecate these by replacing them with bash scripts or creating an alternative in https://github.com/rancher-sandbox/highlander-reusable-workflows/

**Comment by yiannistri** [comment]
In order to create PRs we can use either the `gh` cli (which should be installed by default on the runner) or the `actions/github-script@v7` GHA:
```
- name: cli
  run: gh pr create -B main -H new-feature --title 'New feature' --body 'Created by Github action'
  env:
    GITHUB_TOKEN: ${{ secrets.CUSTOM_TOKEN }}
```
vs
```
- name: action
  uses: actions/github-script@v7
  with:
    github-token: ${{ secrets.CUSTOM_TOKEN }}
    script: |
      github.rest.pulls.create({
          owner: context.repo.owner,
          repo: context.repo.repo,
          head: 'new-feature',
          base: 'main',
          title: 'New feature',
          body: 'Created by Github action'
        })
```

Thoughts / preferences @alexander-demicev ?

**Comment by Danil-Grigorev** [comment]
From the turtles side there is also needed: https://github.com/rancher/turtles-docs/issues/94
